#!/usr/bin/env python

"""Rebuild SIFT files generated by VLFeat to conform to the standard format.

"""
import sys

if len(sys.argv) != 2:
    print "Usage: fix_vlsift.py filename"

fn = sys.argv[1]
f = open(fn, 'r')
data = f.readlines()
f.close()

if len(data[0].split()) == 2:
    raise RuntimeError('Looks like the file is already in SIFT format.')
N = len(data)
keylen = len(data[1].split()) - 4

print "Backing up old file..."
bak = open(fn + '.bak', 'w')
bak.writelines(data)
bak.close()

print "Rewriting file..."
new = open(fn, 'w')
new.writelines(['%d %d\n' % (N, keylen)] + data)
new.close()
