from glob import glob

env = Environment()
env.ParseConfig('python-config --includes')
env.Replace(CCFLAGS=['-O2','-ggdb','-ansi','-pedantic'])
env.SharedLibrary('fast_', glob('fast_*.c') + ['nonmax.c'])
